export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const ORDER_STEP_CHANGE = 'ORDER_STEP_CHANGE';
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';

export default {
  UPDATE_CURRENT_USER,
  ORDER_STEP_CHANGE,
  ADD_ITEM_TO_ORDER,
};
