export const LOGGED_USER_LOADED = 'LOGGED_USER_LOADED';
export const ORDER_STEP_CHANGE = 'ORDER_STEP_CHANGE';
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';

export default {
  LOGGED_USER_LOADED,
  ORDER_STEP_CHANGE,
  ADD_ITEM_TO_ORDER,
};
