export const LOGGED_USER_LOADED = 'LOGGED_USER_LOADED';
export const LOGGED_USER_UNLOADED = 'LOGGED_USER_UNLOADED';
export const ORDER_STEP_CHANGE = 'ORDER_STEP_CHANGE';

export default {
  LOGGED_USER_LOADED,
  LOGGED_USER_UNLOADED,
  ORDER_STEP_CHANGE,
};
